# Note that all secrets are stored on the CircleCI server. They will not appear in this file.

# Details when the `build` and `publish` steps will be run
workflows:
  version: 2
  main:
    jobs:
      # Always `build` any commits
      - build:
          filters:
            tags:
              only: /.*/
      # Only `publish` commits that have a git release label!
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/


version: 2
jobs:
  # The `build` step that's referenced above
  build:
    docker:
      - image: cibuilds/chrome-extension:latest
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: echo "You can also install Yarn, NPM, or anything else you need to use to build and test your extension."
      - run:
          name: "Run Tests"
          command: echo "Run any tests here."
      - run:
          name: "Package Extension"
          command: git archive -o extension.zip HEAD
      # Use workspaces to move files between `build` and `publish`
      - persist_to_workspace:
          root: /root/project
          paths:
            - extension.zip

  # The `published` step that's referenced above
  publish:
    docker:
      - image: cibuilds/chrome-extension:latest
    environment:
      # Not a secret :)
      - APP_ID: ndgeljpfnjlnmbgekhjkchhhgoiipnfi
    steps:
      - attach_workspace:
          at: /root/workspace
      - run:
          name: "Publish to the Google Chrome Store"
          # Note this publish command is built into the custom docker image
          # https://github.com/cibuilds/chrome-extension
          command: publish /root/workspace/extension.zip